import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex flex-row gap-4 h-12 p-3 bg-slate-200">
          <a href="/pdf">PDF</a>
          <a href="/json">JSON</a>
          <a href="/web">WEB</a>
          <a href="/calendar">CALENDAR</a>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
